version: "3.8"
services:
  hubspot-prospects:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hubspot-prospects
    env_file: '.env'
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true




